# Generated by Django 3.0.4 on 2021-09-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taguser',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagapp.TagModel'),
        ),
    ]
