# Generated by Django 3.0.4 on 2021-09-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0002_auto_20210925_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='taguser',
            name='content',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
